baseurl      = "https://AlumniClubFBB.github.io"
title        = "FBB Alumni Club"
languageCode = "ru"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"

[params]
  # Subtitle for home
  homeSubtitle = "Клуб выпускников ФББ МГУ"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "FBB Alumni Club"
    subtitle = "Клуб выпускников ФББ МГУ"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "fbb alumni club"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "prize"
    name       = "Премия клуба"
    url        = "/prize"