name: "Hugo Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Read .env
        id: env-project
        run: |
          . ./.env
          echo "::set-output name=HUGO_VERSION::${HUGO_VERSION}"
          echo "::set-output name=EXTERNAL_DOMAIN::${EXTERNAL_DOMAIN}"
          echo "::set-output name=GIT_DEPLOY_BRANCH::${GIT_DEPLOY_BRANCH}"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version:  '${{ steps.env-project.outputs.HUGO_VERSION }}'
          extended: true

      - name: Set CNAME
        env:
          EXTERNAL_DOMAIN: '${{ steps.env-project.outputs.EXTERNAL_DOMAIN }}'
        run: echo $EXTERNAL_DOMAIN > ./static/CNAME

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ steps.env-project.outputs.GIT_DEPLOY_BRANCH }}
          publish_dir: ./public
